### ISSUE TITLE
DeprecationWarning: aysncio.Task.all_tasks(loop)

### ISSUE THREAD

**Issue by reservoirinvest** [uogbuji/techwriting#1]
There is a _DeprecationWarning_ in your otherwise [fantastic tutorial code](https://github.com/uogbuji/techwriting/blob/master/dataondemandpython/serve_tables_progress.py):
<code>#Check if this is the last remaining task, and exit if so
num_active_tasks = [ task for task in asyncio.Task.all_tasks(loop) if not task.done() ]</code>

Please remove *Task* from asyncio.**Task**.all_tasks(loop)

Thanks!

**Comment by uogbuji** [comment]
True, thanks. as the docs say.

>Deprecated since version 3.7, will be removed in version 3.9: Do not call this as a task method. Use the `asyncio.all_tasks()` function instead.

Of course this is an unfortunately narrow range. I'll have to decide whether to make 3.7 the minimum for the tutorial (previously 3.6) or add a version test. There is still a lot of 3.6 out there in distribution defaults, but a version test is a clumsy distraction. Hmm.

**Comment by uogbuji** [comment]
OK decided on the future ;)
